"""Add recipe metadata fields

Revision ID: 8b9d4b45f14b
Revises: 
Create Date: 2025-12-30 11:41:52.292221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9d4b45f14b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.add_column('recipes', sa.Column('calories', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('protein_g', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('carbs_g', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('fat_g', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('review', sa.Text(), nullable=True))
    op.add_column('recipes', sa.Column('photo_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'photo_url')
    op.drop_column('recipes', 'review')
    op.drop_column('recipes', 'rating')
    op.drop_column('recipes', 'fat_g')
    op.drop_column('recipes', 'carbs_g')
    op.drop_column('recipes', 'protein_g')
    op.drop_column('recipes', 'calories')
    op.drop_column('recipes', 'is_public')
    # ### end Alembic commands ###
